dist: xenial
sudo: false
language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q
    - sudo apt-get install -qq

install:
    # first we create a directory for the CMake binaries
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    # we use wget to fetch the cmake binaries
    - travis_retry wget --no-check-certificate https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.tar.gz
    # extract the binaries; the output here is quite lengthy,
    # so we swallow it to not clutter up the travis console
    - tar -xvf cmake-3.10.3-Linux-x86_64.tar.gz > /dev/null
    - mv cmake-3.10.3-Linux-x86_64 cmake-install
    # add both the top-level directory and the bin directory from the archive
    # to the system PATH. By adding it to the front of the path we hide the
    # preinstalled CMake with our own.
    - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
    # don't forget to switch back to the main build directory once you are done
    - cd ${TRAVIS_BUILD_DIR}
    
    - if [ "§CXX" = "g++" ]; then sudo apt-get install -qq g++-7; fi
    - if [ "§CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7";fi
    - if [ "§CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi
    - if [ "§CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
    
    - if [ "§CXX" = "clang" ]; then sudo apt-get install -qq clang-7; fi
    - if [ "§CXX" = "clang" ]; then export CXX="clang++-7"; fi
    
script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .