dist: trusty
sudo: false
language: cpp

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
	- sudo add-apt-repository universe
    - sudo apt-get update -q
    - sudo apt install xorg-dev libglu1-mesa-dev g++-7 libglfw3-dev
    - pip install --user cpp-coveralls

script:
    - mkdir build
    - cd build
    - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake -DCOVERAGE=1 ..
    - cmake --build .

after_success:
    - coveralls --root .. -E ".*contrib*" -E ".*CMakeFiles.*" -E ".*examples.*"
    