@startuml
!include skin.iuml

enum Key
enum KeyAction
class Client
class RenderContext
class InputListener {
    + Register(Key, KeyAction, Callback)
    + Call(Key, KeyAction)
}

Client .> InputListener
InputListener .u.> Key
InputListener .u.> KeyAction

Client ..> RenderContext : RegisterInputListener()
@enduml